# Generated by Django 5.1.3 on 2025-09-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='last_suggestions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
